setTimeout(()=>{
    document.getElementById('hh').innerHTML=10;
   setTimeout(()=>{
      document.getElementById('hh').innerHTML=9;
      setTimeout(()=>{
        document.getElementById('hh').innerHTML=8;
        setTimeout(()=>{
            document.getElementById('hh').innerHTML=7;
            setTimeout(()=>{
                document.getElementById('hh').innerHTML=6;
                setTimeout(()=>{
                    document.getElementById('hh').innerHTML=5;
                    setTimeout(()=>{
                        document.getElementById('hh').innerHTML=4;
                        setTimeout(()=>{
                            document.getElementById('hh').innerHTML=3;
                            setTimeout(()=>{
                                document.getElementById('hh').innerHTML=2;
                                setTimeout(()=>{
                                    document.getElementById('hh').innerHTML=1;
                                    setTimeout(()=>{
                                        document.getElementById('hh').innerHTML='74 th Happy Independence day!';
                                      },1000);
                                  },1000);
                              },1000);
                          },1000);
                      },1000);
                  },1000);
              },1000);
          },1000);
      },1000);
   },1000)
},1000);

